POST http://localhost:3001/api/order
Content-Type: application/json

{
  "orderNumber":123,
  "userId":"userID",
  "user":"user firstname + lastname",
  "totalCost": 540,
  "shipping": "Truck",
  "sent": false,
  "products": "Småfågel",
  "adress": {
    "street": "Kungsgatan 5",
    "zipCode": 51164,
    "city": "Skövde"
    }
  }

###
GET http://localhost:3001/api/order