GET http://localhost:3001/api/user/all

###

GET http://localhost:3001/api/user/60aba162010c3c2f005643e8

###

POST http://localhost:3001/api/user/register
Content-Type: application/json

{
  "email": "adminAnders@gåslever.eu",
  "password": "123"
}

###

POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "email": "adminAnders@gåslever.eu",
  "password": "123"
}

###

POST http://localhost:3001/api/user/logout

###

GET http://localhost:3001/api/user/read-cookies
