GET http://localhost:3001/api/user/all

###

POST http://localhost:3001/api/user/register
Content-Type: application/json

{
  "email": "pallepastejsandrakompis@gåslever.eu",
  "password": "123",
  "isAdmin": "false"
}

###

POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "email": "pallepastej@gåslever.eu",
  "password": "123",
  "isAdmin": "false"
}

###

POST http://localhost:3001/api/user/logout

###

GET http://localhost:3001/api/user/read-cookies
