export interface Product {
    productname: string
    cardtype: string
    color: string
    cardtext: string
    expansion: string
    cmc: number
    image: string
    id: number
    price: number
    producttype: string
    view: boolean,
    rating: number
}

export const products: Product[] = [
        {productname: "Ancestor's Chosen",
        cardtype:"Creature — Human Cleric",
        color:"White",
        cardtext:"First strike (This creature deals combat damage before creatures without first strike.)\nWhen Ancestor's Chosen enters the battlefield, you gain 1 life for each card in your graveyard.",
        expansion:"Tenth Edition",
        cmc:7.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130550&type=card",
        id:1,
        price:39,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Nightmare",
        cardtype:"Creature — Nightmare Horse",
        color:"Black",
        cardtext:"Flying: This creature can't be blocked except by creatures with flying or reach. Nightmare's power and toughness are each equal to the number of Swamps you control",
        expansion:"Tenth Edition",
        cmc:6.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129659&type=card",
        id:2,
        price:49,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Nekrataal",
        cardtype:"Creature — Human Assassin",
        color:"Black",
        cardtext:"First strike, When Nekrataal enters the battlefield, destroy target nonartifact, nonblack creature. That creature can't be regenerated.",
        expansion:"Tenth Edition",
        cmc:4.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129658&type=card",
        id:3,
        price:19,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Hidden Horror",
        cardtype:"Creature — Horror",
        color:"Black",
        cardtext:"When Hidden Horror enters the battlefield, sacrifice it unless you discard a creature card.",
        expansion:"Tenth Edition",
        cmc:3.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135234&type=card",
        id:4,
        price:59,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Rule of Law",
        cardtype:"Enchantment",
        color:"White",
        cardtext:"Each player can't cast more than one spell each turn.",
        expansion:"Tenth Edition",
        cmc:3.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=136291&type=card",
        id:5,
        price:79,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Beacon of Unrest",
        cardtype:"Sorcery",
        color:"Black",
        cardtext:"Put target artifact or creature card from a graveyard onto the battlefield under your control. Shuffle Beacon of Unrest into its owner's library.",
        expansion:"Tenth Edition",
        cmc:5.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135270&type=card",
        id:6,
        price:49,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Agonizing Memories",
        cardtype:"Sorcery",
        color:"Black",
        cardtext:"Look at target player's hand and choose two cards from it. Put them on top of that player's library in any order.",
        expansion:"Tenth Edition",
        cmc:4.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135228&type=card",
        id:7,
        price:119,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Dreamborn Muse",
        cardtype:"Creature — Spirit",
        color:"Blue",
        cardtext:"First strike (This creature deals combat damage before creatures without first strike.)\nWhen Ancestor's Chosen enters the battlefield, you gain 1 life for each card in your graveyard.",
        expansion:"Tenth Edition",
        cmc:4.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135246&type=card",
        id:8,
        price:19,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Evacuation",
        cardtype:"Instant",
        color:"Blue",
        cardtext:"Return all creatures to their owners' hands.",
        expansion:"Tenth Edition",
        cmc:5.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129541&type=card",
        id:9,
        price:89,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Denizen of the Deep",
        cardtype:"Creature — Serpent",
        color:"Blue",
        cardtext:"When Denizen of the Deep enters the battlefield, return each other creature you control to its owner's hand.",
        expansion:"Tenth Edition",
        cmc:8.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=135250&type=card",
        id:10,
        price:79,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Honor Guard",
        cardtype:"Creature — Human Soldier",
        color:"White",
        cardtext:"First strike (This creature deals combat damage before creatures without first strike.)\nWhen Ancestor's Chosen enters the battlefield, you gain 1 life for each card in your graveyard.",
        expansion:"Tenth Edition",
        cmc:1.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129595&type=card",
        id:11,
        price:49,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "High Ground",
        cardtype:"Enchantment",
        color:"White",
        cardtext:"Each creature you control can block an additional creature each combat.",
        expansion:"Tenth Edition",
        cmc:1.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132145&type=card",
        id:12,
        price:69,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Hail of Arrows",
        cardtype:"Instant",
        color:"White",
        cardtext:"Hail of Arrows deals X damage divided as you choose among any number of target attacking creatures.",
        expansion:"Tenth Edition",
        cmc:1.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132107&type=card",
        id:13,
        price:39,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Cho-Manno",
        cardtype:"Legendary Creature — Human Rebel",
        color:"White",
        cardtext:"Prevent all damage that would be dealt to Cho-Manno, Revolutionary.",
        expansion:"Tenth Edition",
        cmc:4.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130554&type=card",
        id:14,
        price:59,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Bandage",
        cardtype:"Instant",
        color:"White",
        cardtext:"Prevent the next 1 damage that would be dealt to any target this turn. Draw a card.",
        expansion:"Tenth Edition",
        cmc:1.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=132106&type=card",
        id:15,
        price:79,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Ballista Squad",
        cardtype:"Creature — Human Rebel",
        color:"White",
        cardtext:"Ballista Squad deals X damage to target attacking or blocking creature.",
        expansion:"Tenth Edition",
        cmc:4.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129477&type=card",
        id:16,
        price:109,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Angel of Mercy",
        cardtype:"Creature — Angel",
        color:"White",
        cardtext:"Flying, When Angel of Mercy enters the battlefield, you gain 3 life.",
        expansion:"Tenth Edition",
        cmc:5.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129465&type=card",
        id:17,
        price:99,
        producttype:"single",
        view:true,
        rating: 4,
        },
        {productname: "Nomad Mythmaker",
        cardtype:"Creature — Human Nomad Cleric",
        color:"White",
        cardtext:"Put target Aura card from a graveyard onto the battlefield under your control attached to a creature you control.",
        expansion:"Tenth Edition",
        cmc:3.0,
        image:"http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=130547&type=card",
        id:18,
        price:59,
        producttype:"single",
        view:true,
        rating: 4,
        },
    ]